package com.medfusion.ai.domain.model

/**
 * Patient-friendly medical translation (Phase 5.6). Generated by the AI from the
 * doctor's diagnosis, notes, prescription and care plan — the clinical record is
 * NEVER modified; this is an additional explanation shown only to the patient.
 */
data class PatientExplanation(
    /** The diagnosis explained in simple language. */
    val whatDoctorFound: String,
    /** Each prescribed medicine: what it does and why it matters. */
    val medicines: List<MedicineExplanation>,
    /** Daily instructions: rest, hydration, food, restrictions, sleep… */
    val whatToDo: List<String>,
    /** What improvement to expect and how long recovery usually takes. */
    val recovery: String,
    /** When to seek medical attention. */
    val warningSigns: List<String>,
)

data class MedicineExplanation(
    val name: String,
    val purpose: String,
)
